const $=id=>document.getElementById(id);
function notice(t,error=false){const e=$("notice");e.textContent=t;e.hidden=false;e.classList.toggle("error",error)}
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
const saved=()=>{try{return JSON.parse(localStorage.getItem("rfc_devices")||"[]")}catch{return[]}};
const save=x=>localStorage.setItem("rfc_devices",JSON.stringify(x));
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function ago(v){if(!v)return"Belum terhubung";let n=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/1000));return n<10?"Baru saja":n<60?`${n} detik lalu`:n<3600?`${Math.floor(n/60)} menit lalu`:`${Math.floor(n/3600)} jam lalu`}
async function refresh(){let list=saved();if(!list.length){$("devices").innerHTML='<div class="empty">Belum ada perangkat. Tekan <b>Buat perangkat</b> untuk mulai.</div>';return}let rows=await Promise.all(list.map(async d=>{try{return {...d,...await api(`/api/devices?deviceId=${encodeURIComponent(d.deviceId)}`,{headers:{"x-control-token":d.controlToken}})}}catch(e){return {...d,failed:true}}}));$("devices").innerHTML=rows.map(d=>`<article class="device"><div class="device-top"><div class="device-icon">📱</div><div class="device-info"><h3>${esc(d.name||"Android device")}</h3><div class="device-id">${esc(d.deviceId)}</div></div><span class="status ${d.online&&!d.failed?"online":""}">${d.online&&!d.failed?"Online":"Offline"}</span></div><div class="device-meta">Perintah: <b>${esc(d.command||"OFF")}</b> · ${esc(d.failed?"Gagal membaca status":ago(d.lastSeenAt))}</div><div class="device-actions"><button class="action on" data-c="ON" data-id="${esc(d.deviceId)}">☀ Nyalakan</button><button class="action off" data-c="OFF" data-id="${esc(d.deviceId)}">◐ Matikan</button><button class="action remove" data-r="${esc(d.deviceId)}">Hapus dari daftar</button></div></article>`).join("");$("devices").querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>command(b.dataset.id,b.dataset.c));$("devices").querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{save(saved().filter(d=>d.deviceId!==b.dataset.r));refresh()})}
async function command(id,cmd){let d=saved().find(x=>x.deviceId===id);try{await api("/api/command",{method:"POST",headers:{"x-control-token":d.controlToken},body:JSON.stringify({deviceId:id,command:cmd})});notice(`Perintah ${cmd} dikirim. APK harus sudah terhubung.`);refresh()}catch(e){notice(e.message,true)}}
$("createBtn").onclick=async()=>{let b=$("createBtn");b.disabled=true;try{let d=await api("/api/devices",{method:"POST",body:"{}"});$("pairCode").textContent=d.pairingCode;$("deviceIdText").textContent=d.deviceId;$("pairCard").hidden=false;save([{deviceId:d.deviceId,controlToken:d.controlToken,name:d.name},...saved().filter(x=>x.deviceId!==d.deviceId)]);notice("Perangkat dibuat. Simpan kode dan masukkan ke APK.");await refresh()}catch(e){notice(e.message,true)}finally{b.disabled=false}};
$("refreshBtn").onclick=refresh;$("closePair").onclick=()=>$("pairCard").hidden=true;$("copyCode").onclick=async()=>{try{await navigator.clipboard.writeText($("pairCode").textContent);notice("Kode disalin")}catch{notice("Salin kode secara manual")}};
api("/api/health").then(()=>$("apiStatus").textContent="API ready").catch(()=>$("apiStatus").textContent="API setup needed");refresh();setInterval(refresh,5000);